{
    'name': "HR Modifier",
    'summary': "Modifies HR Module",
    'description': "Modifies HR Module",
    'author': "Andini",
    'website': "http://www.yourcompany.com",
    'category': 'Uncategorized',
    'version': '1.1.1',
    'depends': ['base', 'hr', 'hr_attendance', 'hr_attendance_geolocation'],
    'data': [
        'security/ir.model.access.csv',
        'security/access_group.xml',
        'data/payroll_type.xml',
        'views/menu.xml',
        'views/res_config_settings.xml',
        'views/hr_employee.xml',
        'views/hr_attendance.xml',
        'views/hr_shift.xml',
        'views/hr_assign_work_time.xml',
        'views/hr_timeoff.xml',
        'views/hr_overtime.xml',
        'views/hr_payroll_template.xml',
        'views/hr_payroll.xml',
        'wizard/create_payroll.xml',
    ],
    'installable': True,
    'application': True,
}
